const state={page:"dashboard",user:"Moin Ahmad",lang:"en",investments:[
{id:"INV-10021",business:"Solar Energy Hub",amount:100000,profit:12000,status:"Active",date:"2026-09-12"},
{id:"INV-10008",business:"Retail Expansion Fund",amount:50000,profit:5500,status:"Active",date:"2026-08-21"}],
transactions:[{id:"TX-9001",type:"Deposit",amount:100000,status:"Verified",date:"2026-09-12"},{id:"TX-8990",type:"Withdrawal",amount:15000,status:"Pending",date:"2026-09-28"}]};

const plans=[
{name:"Starter Growth",min:10000,max:100000,period:"6 Months",returnText:"Variable profit share",tag:"Popular",features:["Minimum Rs. 10,000","6 month term","Profit based on business performance","Monthly reporting"]},
{name:"Business Partner",min:100000,max:500000,period:"12 Months",returnText:"Variable profit share",tag:"",features:["Minimum Rs. 100,000","12 month term","Detailed business reports","Priority support"]},
{name:"Enterprise",min:500000,max:5000000,period:"24 Months",returnText:"Variable profit share",tag:"",features:["Minimum Rs. 500,000","24 month term","Portfolio reporting","Dedicated support"]}];
const businesses=[
{name:"Solar Energy Hub",icon:"☀️",desc:"Commercial solar equipment and installation expansion.",required:2000000,funded:1450000,risk:"Medium",period:"18 Months"},
{name:"Retail Expansion Fund",icon:"🛍️",desc:"Working-capital expansion for a growing retail network.",required:1000000,funded:760000,risk:"Medium",period:"12 Months"},
{name:"Agri Supply Network",icon:"🌾",desc:"Agricultural supply-chain and distribution operations.",required:3000000,funded:920000,risk:"Higher",period:"24 Months"}];

function money(n){return "Rs. "+Number(n).toLocaleString("en-PK")}
function render(){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===state.page));const c=document.getElementById("content");c.innerHTML=pages[state.page]?pages[state.page]():pages.dashboard();bind()}
const pages={
dashboard:()=>`<div class="page"><div class="heading"><div><h1>Welcome back, ${state.user.split(" ")[0]} 👋</h1><div class="muted">Here is your investment overview.</div></div><button class="btn" onclick="go('plans')">+ Invest Now</button></div>
<div class="cards">
${stat("Total Invested",money(150000),"💼")}${stat("Reported Profit",money(17500),"📈")}${stat("Total Value",money(167500),"💰")}${stat("Active Investments",state.investments.length,"📊")}
</div><div class="grid2"><div class="card"><h3 class="section-title">Portfolio Performance</h3><div class="chart">${[40,62,52,76,69,88,82,96,92,100,96,108].map((x,i)=>`<div class="bar" style="height:${x}%"><span>${i+1}</span></div>`).join("")}</div><div class="muted">Illustrative dashboard chart — actual performance depends on verified business reports.</div></div>
<div class="card"><h3 class="section-title">Next Distribution</h3><div style="font-size:28px;font-weight:800">—</div><p class="muted">Distribution dates will appear after the relevant business profit report is approved.</p><button class="btn secondary" onclick="go('investments')">View History</button></div></div>
<div class="card" style="margin-top:18px"><h3 class="section-title">Recent Investments</h3>${investmentTable()}</div>
<div class="footer-note">Important: Investment values and profit figures shown in this demo are sample data. No return is guaranteed.</div></div>`,
plans:()=>`<div class="page"><div class="heading"><div><h1>Investment Plans</h1><div class="muted">Choose a structure and review its terms before investing.</div></div></div><div class="notice">Returns are not guaranteed. Any profit distribution depends on the underlying business performance and applicable agreements.</div><div class="plan-grid">${plans.map((p,i)=>`<div class="card plan"><span class="tag badge blue">${p.tag||"Plan"}</span><h3>${p.name}</h3><div class="muted">${p.period}</div><div class="price">${p.returnText}</div><div class="muted">${money(p.min)} – ${money(p.max)}</div><ul class="features">${p.features.map(f=>`<li>✓ ${f}</li>`).join("")}</ul><button class="btn" onclick="invest(${i})">Invest Now</button></div>`).join("")}</div></div>`,
businesses:()=>`<div class="page"><div class="heading"><div><h1>Business Opportunities</h1><div class="muted">Review business information, funding and risks.</div></div></div><div class="business-grid">${businesses.map((b,i)=>`<div class="card business"><div class="business-img">${b.icon}</div><div class="business-body"><span class="badge ${b.risk==="Higher"?"red":"yellow"}">${b.risk} Risk</span><h3>${b.name}</h3><p class="muted">${b.desc}</p><div class="muted">Funding ${money(b.funded)} / ${money(b.required)}</div><div class="progress"><span style="width:${b.funded/b.required*100}%"></span></div><div style="display:flex;justify-content:space-between;font-size:12px"><span>${Math.round(b.funded/b.required*100)}% funded</span><span>${b.period}</span></div><button class="btn" style="margin-top:14px" onclick="businessDetail(${i})">View Details</button></div></div>`).join("")}</div></div>`,
investments:()=>`<div class="page"><div class="heading"><div><h1>My Investments</h1><div class="muted">Your current investment positions and reported results.</div></div></div><div class="card table-card">${investmentTable(true)}</div></div>`,
transactions:()=>`<div class="page"><div class="heading"><div><h1>Transactions</h1><div class="muted">Deposits, withdrawals and payment records.</div></div><button class="btn" onclick="deposit()">+ Deposit</button></div><div class="card table-card"><table class="table"><thead><tr><th>ID</th><th>Type</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>${state.transactions.map(t=>`<tr><td>${t.id}</td><td>${t.type}</td><td>${money(t.amount)}</td><td><span class="badge ${t.status==="Verified"?"green":"yellow"}">${t.status}</span></td><td>${t.date}</td></tr>`).join("")}</tbody></table></div></div>`,
support:()=>`<div class="page"><div class="heading"><div><h1>Support Center</h1><div class="muted">Create a support ticket or complaint.</div></div><button class="btn" onclick="ticket()">+ New Ticket</button></div><div class="grid2"><div class="card"><h3 class="section-title">Need help?</h3><p class="muted">Our support team can help with account, investment, deposit and withdrawal questions.</p><p>📧 support@example.com</p><p>💬 WhatsApp support can be connected during backend setup.</p></div><div class="card"><h3 class="section-title">Your tickets</h3><div class="empty">No support tickets yet.</div></div></div></div>`,
profile:()=>`<div class="page"><div class="heading"><div><h1>Profile & Security</h1><div class="muted">Manage your account details.</div></div></div><div class="grid2"><div class="card"><h3 class="section-title">Personal Details</h3><div class="form"><label>Full Name<input value="${state.user}"></label><label>Email<input value="moin@example.com"></label><label>Phone<input value="+92 300 0000000"></label><button class="btn" onclick="toast('Profile changes saved in demo')">Save Changes</button></div></div><div class="card"><h3 class="section-title">Security</h3><p>🔐 Password</p><button class="btn secondary" onclick="password()">Change Password</button><p>🛡️ Two-factor authentication</p><button class="btn secondary" onclick="toast('2FA setup will be connected to backend')">Enable 2FA</button></div></div></div>`,
admin:()=>`<div class="page"><div class="heading"><div><h1>Admin Panel</h1><div class="muted">Management controls for the platform.</div></div></div><div class="notice">Demo admin panel. Real approvals, balances and payment processing require a secure server/database with authentication and audit logs.</div><div class="cards">${stat("Investors","128","👥")}${stat("Pending Deposits","7","💳")}${stat("Pending Withdrawals","4","↗️")}${stat("Active Businesses","12","🏢")}</div><div class="grid2"><div class="card"><h3 class="section-title">Pending Requests</h3><table class="table"><tr><th>User</th><th>Type</th><th>Amount</th><th>Action</th></tr><tr><td>Ali R.</td><td>Deposit</td><td>Rs. 50,000</td><td><button class="btn" onclick="toast('Approved in demo')">Approve</button></td></tr><tr><td>Sara K.</td><td>Withdrawal</td><td>Rs. 25,000</td><td><button class="btn secondary" onclick="toast('Request opened')">Review</button></td></tr></table></div><div class="card"><h3 class="section-title">Admin Tools</h3><div class="admin-tabs"><button class="btn secondary" onclick="toast('Investor manager opened')">Investors</button><button class="btn secondary" onclick="toast('Business editor opened')">Businesses</button><button class="btn secondary" onclick="toast('Profit record opened')">Profit Records</button><button class="btn secondary" onclick="toast('Notification composer opened')">Notifications</button><button class="btn secondary" onclick="toast('Settings opened')">Settings</button></div></div></div></div>`
};
function stat(label,value,ico){return `<div class="card stat"><div><div class="label">${label}</div><div class="value">${value}</div></div><div class="ico">${ico}</div></div>`}
function investmentTable(){return `<table class="table"><thead><tr><th>ID</th><th>Business</th><th>Invested</th><th>Reported Profit</th><th>Status</th><th>Date</th></tr></thead><tbody>${state.investments.map(x=>`<tr><td>${x.id}</td><td>${x.business}</td><td>${money(x.amount)}</td><td>${money(x.profit)}</td><td><span class="badge green">${x.status}</span></td><td>${x.date}</td></tr>`).join("")}</tbody></table>`}
function go(p){state.page=p;render();window.scrollTo(0,0)}
function openModal(html){document.getElementById("modalBody").innerHTML=html;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}
function invest(i){let p=plans[i];openModal(`<h2>Invest in ${p.name}</h2><p class="muted">Range: ${money(p.min)} – ${money(p.max)}</p><div class="form"><label>Investment Amount<input id="amt" type="number" min="${p.min}" max="${p.max}" value="${p.min}"></label><label>Select Business<select id="biz">${businesses.map(b=>`<option>${b.name}</option>`).join("")}</select></label><div class="notice">This demo records an investment request only. Payment and legal agreement verification must be completed before real-money processing.</div><button class="btn" onclick="submitInvestment()">Submit Investment Request</button></div>`)}
function submitInvestment(){let n=Number(document.getElementById("amt").value);if(!n){toast("Enter an amount");return}closeModal();toast("Investment request submitted in demo")}
function businessDetail(i){let b=businesses[i];openModal(`<h2>${b.icon} ${b.name}</h2><p>${b.desc}</p><p><b>Required funding:</b> ${money(b.required)}</p><p><b>Funded:</b> ${money(b.funded)}</p><p><b>Investment period:</b> ${b.period}</p><p><b>Risk:</b> ${b.risk}</p><h3>Reports & documents</h3><p class="muted">Business reports, financial statements, agreements and risk disclosures will be uploaded here by the verified administrator.</p><button class="btn" onclick="closeModal();go('plans')">View Investment Plans</button>`)}
function deposit(){openModal(`<h2>Deposit Request</h2><div class="form"><label>Amount<input type="number" placeholder="Rs. 50,000"></label><label>Payment Method<select><option>Bank Transfer</option><option>Supported Payment Gateway</option></select></label><label>Transaction ID<input placeholder="Enter transaction ID"></label><div class="notice">Never send money to an unverified account. Real payment instructions should be configured on the secure backend.</div><button class="btn" onclick="closeModal();toast('Deposit submitted for verification in demo')">Submit Deposit</button></div>`)}
function ticket(){openModal(`<h2>New Support Ticket</h2><div class="form"><label>Subject<input placeholder="What do you need help with?"></label><label>Message<textarea rows="5" placeholder="Describe your issue"></textarea></label><button class="btn" onclick="closeModal();toast('Ticket created in demo')">Create Ticket</button></div>`)}
function password(){openModal(`<h2>Change Password</h2><div class="form"><label>Current Password<input type="password"></label><label>New Password<input type="password"></label><label>Confirm Password<input type="password"></label><button class="btn" onclick="closeModal();toast('Password changed in demo')">Update Password</button></div>`)}
function toast(msg){let x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2500)}
function bind(){document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>go(n.dataset.page));document.getElementById("menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("open");document.getElementById("logout").onclick=()=>toast("Demo logout — connect real authentication in backend");document.getElementById("globalSearch").oninput=e=>{if(e.target.value.trim())toast("Search is ready for backend integration")}}
render();